# Get all
GET http://localhost:8080/api/quizzes
Accept: application/json

###

# Create
POST http://localhost:8080/api/quizzes
Content-Type: application/json
Accept: application/json

{
  "title": "Sample quiz",
  "questions": []
}